### ISSUE TITLE
import existing (RISE) slideshow as nbpresent

### ISSUE THREAD

**Issue by bollwyvl** [Anaconda-Server/nbpresent#24]
### User story
> As a RISE user, I want to try out my existing slides as an nbpresent presentation.

### Tasks
- [ ] load `//cell/*/metadata/slideshow` into `//metadata/nbpresent/slides/*`
   -  _I don't think these need to be bidrectional at this point?_
  - [ ] re-implement the cell->((sub)slide|fragment|note) stream mechanism
  - [ ] allow for "whole" cell part (js/css)
- [ ] ui
  - [ ] opt-in for translation?
    - might as well be automatic (without saving), with a toast notification
  - [ ] notes
  - [ ] fragment build
  - [ ] up/down slides
  - [ ] navigator (blarg)
  - [ ] verify mathjax

most of the esoteric reveal functions were hard to get to short of direction use of the API (background, parallax, autoplay, themes), so such features can be deferred.

**Comment by bollwyvl** [comment]
This is in #34. It doesn't handle fragments or notes.

**Comment by damianavila** [comment]
#34 was merged... do you want to keep this still open?

**Comment by bollwyvl** [comment]
It still doesn't do subslides...

**Comment by damianavila** [comment]
Yep... this is why I asked before closing... :stuck_out_tongue_winking_eye:
